/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppContainer: typeof import('./src/components/organisms/AppContainer/AppContainer.vue')['default']
    ExerciseAbout: typeof import('./src/components/molecules/ExerciseAbout/ExerciseAbout.vue')['default']
    ExerciseCard: typeof import('./src/components/molecules/ExerciseCard/ExerciseCard.vue')['default']
    ExerciseCounter: typeof import('./src/components/molecules/ExerciseCounter/ExerciseCounter.vue')['default']
    ExerciseEdit: typeof import('./src/components/molecules/dialog/ExerciseEdit/ExerciseEdit.vue')['default']
    ExerciseHand: typeof import('./src/components/atoms/ExerciseHand/ExerciseHand.vue')['default']
    ExerciseHangboard: typeof import('./src/components/atoms/ExerciseHangboard/ExerciseHangboard.vue')['default']
    ExerciseList: typeof import('./src/components/organisms/ExerciseList/ExerciseList.vue')['default']
    ExerciseName: typeof import('./src/components/atoms/ExerciseName/ExerciseName.vue')['default']
    HangboardAdd: typeof import('./src/components/molecules/dialog/HangboardAdd/HangboardAdd.vue')['default']
    HangboardSelect: typeof import('./src/components/molecules/HangboardSelect/HangboardSelect.vue')['default']
    MapContainer: typeof import('./src/components/molecules/MapContainer/MapContainer.vue')['default']
    MissingHangboard: typeof import('./src/components/molecules/dialog/MissingHangboard/MissingHangboard.vue')['default']
    NewContentAvailable: typeof import('./src/components/molecules/NewContentAvailable/NewContentAvailable.vue')['default']
    NewsCards: typeof import('./src/components/molecules/NewsCards/NewsCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscribeToApp: typeof import('./src/components/molecules/dialog/SubscribeToApp/SubscribeToApp.vue')['default']
    Walkthrough: typeof import('./src/components/molecules/dialog/Walkthrough/Walkthrough.vue')['default']
    WorkoutBluetooth: typeof import('./src/components/atoms/WorkoutBluetooth/WorkoutBluetooth.vue')['default']
    WorkoutCommunityFilter: typeof import('./src/components/molecules/dialog/WorkoutCommunityFilter/WorkoutCommunityFilter.vue')['default']
    WorkoutComplete: typeof import('./src/components/molecules/dialog/WorkoutComplete/WorkoutComplete.vue')['default']
    WorkoutSave: typeof import('./src/components/molecules/dialog/WorkoutSave/WorkoutSave.vue')['default']
    WorkoutShare: typeof import('./src/components/atoms/WorkoutShare/WorkoutShare.vue')['default']
    WorkoutSubscribe: typeof import('./src/components/atoms/WorkoutSubscribe/WorkoutSubscribe.vue')['default']
    WorkoutSummary: typeof import('./src/components/molecules/WorkoutSummary/WorkoutSummary.vue')['default']
    WorkoutTimer: typeof import('./src/components/organisms/WorkoutTimer/WorkoutTimer.vue')['default']
  }
}
